# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 15.5.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies and build
        run: cd $GITHUB_WORKSPACE && yarn install && npm run build

      - name: package the dist
        run: cd $GITHUB_WORKSPACE && tar cjf authmachine-frontend-customer-portal.tar.bz2 build/

      - name: set up ssh key for auth
        run: echo "${{ secrets.PRODUCTION_UPDATER_SSH_KEY }}" > /tmp/ssh-key && chmod 600 /tmp/ssh-key

      - name: upload the dist
        run: scp -i /tmp/ssh-key -o "StrictHostKeyChecking=no" $GITHUB_WORKSPACE/authmachine-frontend-customer-portal.tar.bz2 production-updater@vanhalen.openunited.com:/home/production-updater/

      - name: trigger deploy
        run: ssh -i /tmp/ssh-key -o "StrictHostKeyChecking=no" production-updater@vanhalen.openunited.com /home/production-updater/update-authmachine-frontend-customer-portal.sh

      - name: remove ssh key
        run: rm -f /tmp/ssh-key
